services:
  - type: web
    name: oral-cancer-detection
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        fromEnv: PORT
    healthCheckPath: /health
    httpPort: 8000
    rootDirectory: ./
    
  - type: static
    name: oral-cancer-frontend
    env: python
    buildCommand: ""
    startCommand: ""
    staticDirs:
      - directory: ./
        buildCommand: ""
        entrypoint: ""
        include: ["simple_frontend.html"]
